pull_request_rules:                   # Define rules that apply to pull requests
  - name: automatic merge when CI passes and approved   # Friendly name for this rule
    conditions:                      # Conditions that must be met for the rule to trigger
      - base=main                   # The PR must target the 'main' branch
      - status-success=Backend CI   # The 'Backend CI' workflow must have succeeded
      - status-success=Frontend CI  # The 'Frontend CI' workflow must have succeeded
      - approved-reviews-by>=1      # The PR must have at least one approving review
    actions:                       # Actions Mergify will perform when conditions are met
      update_branch:               # Automatically update the branch if it's behind main
        method: rebase             # Use rebase to update the branch (can also be merge)
      merge:                       # Automatically merge the PR
        method: squash             # Use squash merge method (squashes all commits into one)
        commit_message_template: |  # Template for the merge commit message
          {{ title }}              # Insert the PR title
          
          {{ body }}               # Insert the PR description/body
