name: Backend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'todogithubactionsbackend/**'
  pull_request:
    branches: [main]
    paths:
      - 'todogithubactionsbackend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: todogithubactionsbackend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Set MongoDB URI (from GitHub secret)
        run: echo "SPRING_DATA_MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV

      - name: Run Maven tests
        run: mvn clean test
        env:
          SPRING_DATA_MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Deploy to Render (CD)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
